grafana:
  image: grafana/grafana
  links:
  - prometheusapp:prometheus-app
  ports:
  - 80:3000
prometheusapp:
  command:
  - -config.file=/opt/prometheus/prometheus.yml
  - -storage.local.path=/data
  - -web.console.libraries=/etc/prometheus/console_libraries
  - -web.console.templates=/etc/prometheus/consoles
  image: prom/prometheus
  links:
  - prometheusgateway:prometheus-gateway
  volumes:
  - /Users/rprakashg/github/rprakashg/prometheus-on-eb/prometheus:/opt/prometheus
  - /data/prometheus:/data
prometheusgateway:
  command:
  - -persistence.file
  - /data/pushgateway.dat
  image: prom/pushgateway
  ports:
  - 9091:9091
  volumes:
  - /data/prometheus_gateway:/data
